name: 'Library and example builds'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install depends
      run: sudo apt install meson libwayland-dev libgtk-3-dev libgirepository1.0-dev gtk-doc-tools
    - name: Meson
      run: meson build
    - name: Build
      run: ninja -C build
